-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "turns" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "session_id" INTEGER not null REFERENCES "sessions"("id"),
  "role" TEXT CHECK ("role" IN ('user', 'assistant', 'system')),
  "status" TEXT CHECK ("status" IN ('pending', 'running', 'complete', 'interrupted', 'failed')),
  "started_at" TEXT,
  "ended_at" TEXT,
  "tokens_in" INTEGER,
  "tokens_out" INTEGER,
  "cost" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "turns_uuid_unique" ON "turns" ("uuid");
