-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "sessions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "workspace_id" INTEGER not null REFERENCES "workspaces"("id"),
  "title" TEXT,
  "driver_kind" TEXT CHECK ("driver_kind" IN ('claude', 'codex', 'cursor', 'opencode', 'grok')),
  "provider_session_id" TEXT,
  "state" TEXT CHECK ("state" IN ('idle', 'running', 'awaiting-approval', 'awaiting-input', 'stopped', 'failed')),
  "runtime_mode" TEXT,
  "interaction_mode" TEXT CHECK ("interaction_mode" IN ('streaming', 'buffered')),
  "last_seq" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "sessions_uuid_unique" ON "sessions" ("uuid");
