-- @generated by `buddy migrate:regenerate` — edits will be overwritten
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "session_id" INTEGER,
  "turn_id" INTEGER,
  "seq" INTEGER not null,
  "type" TEXT not null,
  "payload" TEXT,
  "at" INTEGER,
  "command_id" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_events" ("id", "session_id", "turn_id", "seq", "type", "payload", "at", "command_id", "created_at", "updated_at", "uuid") SELECT "id", "session_id", "turn_id", "seq", "type", "payload", "at", "command_id", "created_at", "updated_at", "uuid" FROM "events";
DROP TABLE "events";
ALTER TABLE "_qb_tmp_events" RENAME TO "events";
CREATE UNIQUE INDEX IF NOT EXISTS "events_uuid_unique" ON "events" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
