-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "approvals" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "session_id" INTEGER not null REFERENCES "sessions"("id"),
  "request_id" TEXT not null,
  "tool_name" TEXT not null,
  "args_digest" TEXT,
  "decision" TEXT CHECK ("decision" IN ('pending', 'allowed', 'denied', 'expired')),
  "scope" TEXT CHECK ("scope" IN ('once', 'session', 'workspace', 'always')),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "approvals_uuid_unique" ON "approvals" ("uuid");
