-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "workspaces" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "profile_id" INTEGER not null REFERENCES "profiles"("id"),
  "name" TEXT not null,
  "path" TEXT not null,
  "vcs_root" TEXT,
  "default_branch" TEXT,
  "trusted" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "workspaces_uuid_unique" ON "workspaces" ("uuid");
