-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "checkpoints" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "session_id" INTEGER not null REFERENCES "sessions"("id"),
  "turn_id" INTEGER,
  "kind" TEXT CHECK ("kind" IN ('turn-start', 'turn-end', 'manual')),
  "vcs_ref" TEXT,
  "dirty_files_snapshot" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "checkpoints_uuid_unique" ON "checkpoints" ("uuid");
