-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "provider_instances" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "profile_id" INTEGER not null REFERENCES "profiles"("id"),
  "driver_kind" TEXT CHECK ("driver_kind" IN ('claude', 'codex', 'cursor', 'opencode', 'grok')),
  "config" TEXT,
  "status" TEXT CHECK ("status" IN ('unknown', 'ready', 'unauthenticated', 'unavailable', 'failed')),
  "binary_path" TEXT,
  "resolved_home" TEXT,
  "version" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "provider_instances_uuid_unique" ON "provider_instances" ("uuid");
