-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "command_receipts" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "command_id" TEXT not null,
  "seqs" TEXT,
  "at" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "command_receipts_command_id_unique" ON "command_receipts" ("command_id");
CREATE UNIQUE INDEX IF NOT EXISTS "command_receipts_uuid_unique" ON "command_receipts" ("uuid");
