-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "profiles" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "icon" TEXT,
  "tint" TEXT,
  "position" INTEGER,
  "settings" TEXT,
  "last_active_workspace_id" INTEGER,
  "archived" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "profiles_uuid_unique" ON "profiles" ("uuid");
