-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "session_id" INTEGER not null REFERENCES "sessions"("id"),
  "turn_id" INTEGER REFERENCES "turns"("id"),
  "seq" INTEGER not null,
  "type" TEXT not null,
  "payload" TEXT,
  "command_id" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "events_uuid_unique" ON "events" ("uuid");
